name: "[Bot] Run sonarqube code scanning'"
run-name: "@Desktop • Test App triggered by ${{ github.event_name == 'workflow_dispatch' && inputs.login || github.actor }} ${{ format('on ref {0}', github.ref_name) }}"

on:
  push:
    branches:
      - develop
      - support/LIVE-9378-add-sonarqube-integration
  workflow_dispatch:
    inputs:
      ref:
        description: the branch which triggered this workflow
        required: false
      login:
        description: The GitHub username that triggered the workflow
        required: true
      base_ref:
        description: The base branch to merge the head into when checking out the code
        required: false
      draft:
        description: true if the PR is in draft
        required: false
        default: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name != 'develop' && github.ref || github.run_id }}

env:
  REFNAME: ${{ (github.event_name == 'workflow_dispatch' && (inputs.ref || github.ref_name)) || github.sha }}

jobs:
  
  run-sonarqube-bot:
    name: "Run Sonarqube bot"
    env:
      FORCE_COLOR: 3
    runs-on: [ledger-live-4xlarge-linux]
    steps:
      - uses: LedgerHQ/ledger-live/tools/actions/composites/checkout-merge@develop
        with:
          ref: ${{ env.REFNAME }}
          base: ${{ inputs.base_ref }}
      - uses: ./tools/actions/composites/setup-test-desktop
        id: setup-test-desktop
        with:
          skip_builds: true
          aws-access-key: ${{ secrets.AWS_S3_CACHE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_S3_CACHE_SECRET_KEY }}
      - name: Run unit tests
        run: pnpm desktop test:jest
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}